import { Dimensions } from 'react-native';

export const SCREEN = {
  height: Dimensions.get('screen').height,
  width: Dimensions.get('screen').width,
};

export const HORIZONTAL_SPACING = 25;

export const COUNTRY_NAMES_SPANISH_TO_ENGLISH = {
  afganistán: 'afghanistan',
  albania: 'albania',
  argelia: 'algeria',
  andorra: 'andorra',
  angola: 'angola',
  'antigua y barbuda': 'antigua and barbuda',
  argentina: 'argentina',
  armenia: 'armenia',
  australia: 'australia',
  austria: 'austria',
  azerbaiyán: 'azerbaijan',
  bahamas: 'bahamas',
  baréin: 'bahrain',
  bangladés: 'bangladesh',
  barbados: 'barbados',
  bielorrusia: 'belarus',
  bélgica: 'belgium',
  belice: 'belize',
  benín: 'benin',
  bután: 'bhutan',
  bolivia: 'bolivia',
  'bosnia y herzegovina': 'bosnia and herzegovina',
  botsuana: 'botswana',
  brasil: 'brazil',
  brunéi: 'brunei',
  bulgaria: 'bulgaria',
  'burkina faso': 'burkina faso',
  burundi: 'burundi',
  'cabo verde': 'cabo verde',
  camboya: 'cambodia',
  camerún: 'cameroon',
  canadá: 'canada',
  'república centroafricana': 'central african republic',
  chad: 'chad',
  chile: 'chile',
  china: 'china',
  colombia: 'colombia',
  comoras: 'comoros',
  'congo (congo-brazzaville)': 'congo (congo-brazzaville)',
  'costa rica': 'costa rica',
  croacia: 'croatia',
  cuba: 'cuba',
  chipre: 'cyprus',
  'chequia (república checa)': 'czechia (czech republic)',
  'república democrática del congo': 'democratic republic of the congo',
  dinamarca: 'denmark',
  yibuti: 'djibouti',
  dominica: 'dominica',
  'república dominicana': 'dominican republic',
  ecuador: 'ecuador',
  egipto: 'egypt',
  'el salvador': 'el salvador',
  'guinea ecuatorial': 'equatorial guinea',
  eritrea: 'eritrea',
  estonia: 'estonia',
  esuatini: 'eswatini',
  etiopía: 'ethiopia',
  fiyi: 'fiji',
  finlandia: 'finland',
  francia: 'france',
  gabón: 'gabon',
  gambia: 'gambia',
  georgia: 'georgia',
  alemania: 'germany',
  ghana: 'ghana',
  grecia: 'greece',
  granada: 'grenada',
  guatemala: 'guatemala',
  guinea: 'guinea',
  'guinea-bisáu': 'guinea-bissau',
  guyana: 'guyana',
  haití: 'haiti',
  'santa sede': 'holy see',
  honduras: 'honduras',
  hungría: 'hungary',
  islandia: 'iceland',
  india: 'india',
  indonesia: 'indonesia',
  irán: 'iran',
  irak: 'iraq',
  irlanda: 'ireland',
  israel: 'israel',
  italia: 'italy',
  jamaica: 'jamaica',
  japón: 'japan',
  jordania: 'jordan',
  kazajistán: 'kazakhstan',
  kenia: 'kenya',
  kiribati: 'kiribati',
  kuwait: 'kuwait',
  kirguistán: 'kyrgyzstan',
  laos: 'laos',
  letonia: 'latvia',
  líbano: 'lebanon',
  lesoto: 'lesotho',
  liberia: 'liberia',
  libia: 'libya',
  liechtenstein: 'liechtenstein',
  lituania: 'lithuania',
  luxemburgo: 'luxembourg',
  madagascar: 'madagascar',
  malaui: 'malawi',
  malasia: 'malaysia',
  maldivas: 'maldives',
  malí: 'mali',
  malta: 'malta',
  'islas marshall': 'marshall islands',
  mauritania: 'mauritania',
  mauricio: 'mauritius',
  méxico: 'mexico',
  micronesia: 'micronesia',
  moldavia: 'moldova',
  mónaco: 'monaco',
  mongolia: 'mongolia',
  montenegro: 'montenegro',
  marruecos: 'morocco',
  mozambique: 'mozambique',
  'myanmar (antes birmania)': 'myanmar (formerly burma)',
  namibia: 'namibia',
  nauru: 'nauru',
  nepal: 'nepal',
  'países bajos': 'netherlands',
  'nueva zelanda': 'new zealand',
  nicaragua: 'nicaragua',
  níger: 'niger',
  nigeria: 'nigeria',
  'corea del norte': 'north korea',
  'macedonia del norte': 'north macedonia',
  noruega: 'norway',
  omán: 'oman',
  pakistán: 'pakistan',
  palaos: 'palau',
  'estado de palestina': 'palestine state',
  panamá: 'panama',
  'papúa nueva guinea': 'papua new guinea',
  paraguay: 'paraguay',
  perú: 'peru',
  filipinas: 'philippines',
  polonia: 'poland',
  portugal: 'portugal',
  catar: 'qatar',
  rumanía: 'romania',
  rusia: 'russia',
  ruanda: 'rwanda',
  'san cristóbal y nieves': 'saint kitts and nevis',
  'santa lucía': 'saint lucia',
  'san vicente y las granadinas': 'saint vincent and the grenadines',
  samoa: 'samoa',
  'san marino': 'san marino',
  'santo tomé y príncipe': 'sao tome and principe',
  'arabia saudita': 'saudi arabia',
  senegal: 'senegal',
  serbia: 'serbia',
  seychelles: 'seychelles',
  'sierra leona': 'sierra leone',
  singapur: 'singapore',
  eslovaquia: 'slovakia',
  eslovenia: 'slovenia',
  'islas salomón': 'solomon islands',
  somalia: 'somalia',
  sudáfrica: 'south africa',
  'corea del sur': 'south korea',
  'sudán del sur': 'south sudan',
  españa: 'spain',
  'sri lanka': 'sri lanka',
  sudán: 'sudan',
  surinam: 'suriname',
  suecia: 'sweden',
  suiza: 'switzerland',
  siria: 'syria',
  tayikistán: 'tajikistan',
  tanzania: 'tanzania',
  tailandia: 'thailand',
  'timor oriental': 'timor-leste',
  togo: 'togo',
  tonga: 'tonga',
  'trinidad y tobago': 'trinidad and tobago',
  túnez: 'tunisia',
  turquía: 'turkey',
  turkmenistán: 'turkmenistan',
  tuvalu: 'tuvalu',
  uganda: 'uganda',
  ucrania: 'ukraine',
  'emiratos árabes unidos': 'united arab emirates',
  'reino unido': 'united kingdom',
  'estados unidos de américa': 'united states of america',
  uruguay: 'uruguay',
  uzbekistán: 'uzbekistan',
  vanuatu: 'vanuatu',
  venezuela: 'venezuela',
  vietnam: 'vietnam',
  yemen: 'yemen',
  zambia: 'zambia',
  zimbabue: 'zimbabwe',
};
